### ISSUE TITLE
Problem Statement

### ISSUE THREAD

**Issue by enkiluv** [bacchusdd/SoftwareEngineering#1]
Problem Statement는 고객(수혜자)의 관점에서 무엇이 문제이고 무엇을 이루고자 하는지 작성해야 합니다. 개발자 관점에서 무엇을 개발하려한다는 관점이 아닙니다. 원래는 고객과 인터뷰/브레인스토밍을 통해 작성하는 것이나 이번 학기의 특성상 개발팀이 직접 작성하게한 것입니다.

그리고 PS는 요구를 도출할 수 있을 만큼 내용이 있어야 합니다. 지금 작성된 수준은 거의 대부분의 요구를 짐작에 의해 도출해야할 것으로 보입니다.

**Comment by bacchusdd** [comment]
네. 해당 내용 반영하여 수정하겠습니다!
